[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cbin-nn"
version = "0.1.0"
description = "A framework for running Binarized Neural Networks on resource-constrained devices"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.26",
    "tensorflow>=2.15.0",
    "larq>=0.13.3",
]

[project.scripts]
cbin-convert = "cbin_nn.model_converter:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["cbin_nn*"]

[tool.setuptools.package-data]
"cbin_nn" = ["operators/*.c", "operators/*.h"]
